/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve Subscriptions
         * @description Retrieve subscriptions with flexible filtering and pagination.
         *
         *     Supports three access patterns for optimal performance: direct lookup by subscription ID, customer-based retrieval, or general querying with multiple filter options. Results can be sorted and paginated for efficient data handling.
         *
         *     ### Args
         *
         *     - `limit`: Maximum number of results to retrieve (1-1000, defaults to 50)
         *     - `cursor`: Pagination cursor from previous response's `next_cursor` field
         *     - `subscription_id`: Shopify subscription contract ID for direct retrieval:
         *         - Example: `"gid://shopify/SubscriptionContract/123"`
         *         - When provided, returns single subscription or empty list
         *     - `subscription_ids`: List of shopify subscription contract IDs for direct retrieval:
         *         - Example: `["gid://shopify/SubscriptionContract/123", "gid://shopify/SubscriptionContract/456"]`
         *         - When provided, returns list of subscriptions or empty list
         *     - `related_to_customer`: Shopify customer ID to fetch all customer subscriptions:
         *         - Example: `"gid://shopify/Customer/456"`
         *         - Returns all subscriptions for that customer
         *     - `status`: Contract status filter with options:
         *         - `"ACTIVE"`: Currently active subscriptions
         *         - `"CANCELLED"`: Cancelled subscriptions
         *         - `"EXPIRED"`: Expired subscriptions
         *         - `"FAILED"`: Failed subscriptions
         *         - `"PAUSED"`: Temporarily paused subscriptions
         *         - `"STALE"`: Stale subscriptions
         *     - `variant_id`: Composite variant ID filter:
         *         - Format: `"gid://shopify/ProductVariant/{{id}}|{{type}}"`
         *         - Types: `"subscription"` or `"one_time"`
         *         - Example: `"gid://shopify/ProductVariant/42638817034446|subscription"`
         *     - `next_billing_date_min`: Filter subscriptions with next billing on/after date (ISO format)
         *     - `next_billing_date_max`: Filter subscriptions with next billing on/before date (ISO format)
         *     - `created_at_min`: Filter subscriptions created on/after date (ISO format)
         *     - `created_at_max`: Filter subscriptions created on/before date (ISO format)
         *     - `order_by`: Field to sort results by:
         *         - `"next_billing_date"`: Sort by upcoming billing date
         *         - `"created_at"`: Sort by subscription creation date
         *     - `order_by_direction`: Sort direction (`"ASC"` for ascending, `"DESC"` for descending)
         *
         *     ### Returns
         *
         *     **SubscriptionsResponse** containing:
         *
         *     - `subscriptions`: List of subscription contract details
         *     - `next_cursor`: Pagination cursor for retrieving next page (if more results available)
         *
         *     ### Raises
         *
         *     - **HTTPException (400)**: Invalid query filters
         *     - **HTTPException (500)**: Query execution fails
         *
         *     ### Notes
         *
         *     - Direct subscription lookup (by `subscription_id`) is fastest for single subscription retrieval
         *     - Customer-based queries use optimized indexing for efficient customer subscription lookup
         *     - General queries support complex filtering but require proper index configuration
         *     - When no status filter is provided, searches across all subscription statuses
         *     - Pagination uses cursor-based approach for consistent results across pages
         */
        get: operations["retrieve_subscriptions_v1_subscriptions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions/charge-now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Charge Now
         * @description Enqueue subscriptions for immediate charging.
         *
         *     This endpoint allows merchants to manually trigger subscription billing outside the normal schedule. It supports two modes of operation for flexible billing management. The charge is processed asynchronously.
         *
         *     ### Args
         *
         *     - `subscription_ids`: List of specific subscription IDs to charge immediately
         *     - `customer_id`: Customer ID to charge all due subscriptions
         *     - `next_billing_date_reference`: How to calculate the next billing date after charging:
         *         - `"from_today"`: Next date = today + interval
         *         - `"original_next_billing_date"`: Next date = current next_billing_date + interval
         *         - `"leave_as_is"`: Don't change the next billing date
         *     - `notify_customer_about_failed_attempt`: Whether to email customer on failure (default: True)
         *     - `caused_by`: Audit trail identifier (default: "Subscription Charge Now API")
         *
         *     ### Returns
         *
         *     **ChargeNowResponse** containing:
         *
         *     - `subscription_ids`: List of subscription IDs that have been enqueued for charging
         *
         *     ### Raises
         *
         *     - **HTTPException (400)**: Invalid store, or both/neither `subscription_ids` and `customer_id` provided
         *     - **HTTPException (500)**: Internal error during processing
         *
         *     ### Notes
         *
         *     - The charge is processed asynchronously and typically completes within 3-5 seconds
         *     - To verify the charge completed, poll the subscription to check if `next_billing_date` has been updated
         *     - Charging uses idempotency keys based on `next_billing_date` + `contract_id` to prevent duplicate charges on the same day
         *     - When charging by `customer_id`, only subscriptions due today or earlier are charged
         *     - To charge future-dated subscriptions, you must provide specific `subscription_ids`
         *     - Multiple subscriptions for the same customer are bundled into a single charge
         */
        post: operations["charge_now_v1_subscriptions_charge_now_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions/add-line-item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Line Item
         * @description Add a line item (product) to an existing subscription contract.
         *
         *     Supports both one-time and subscription products. One-time products are identified
         *     by custom attributes with `type: one_time`. The operation creates a draft of the
         *     subscription, adds the line item, and commits the changes.
         *
         *     ### Args
         *
         *     - `subscription_id`: ID of the subscription contract to modify
         *     - `customer_id`: Shopify customer ID for validation (must match contract owner)
         *     - `line_item`: Line item details containing:
         *         - `product_variant_id`: The product variant to add
         *         - `current_price`: Price for the line item (optional - if provided will be used, otherwise fetched from Shopify)
         *         - `quantity`: Quantity to add
         *         - `selling_plan_id`: Selling plan ID (required for subscription items, optional for one-time)
         *         - `custom_attributes`: Custom attributes (use `type: one_time` for one-time products)
         *         - `type`: Line item type (`subscription` or `one_time`)
         *     - `caused_by`: Email or identifier of who initiated this action (for audit trail)
         *
         *     ### Returns
         *
         *     **SubscriptionResponse** containing:
         *
         *     - `subscription`: The complete modified subscription contract with all details
         *
         *     ### Raises
         *
         *     - **HTTPException (400)**: Invalid request parameters
         *     - **HTTPException (403)**: Customer ID doesn't match contract owner
         *     - **HTTPException (404)**: Contract not found
         *     - **HTTPException (500)**: Failed to add line item
         *
         *     ### Notes
         *
         *     - Creates a contract draft, modifies it, and commits the changes
         *     - Validates customer ownership before making changes
         *     - All operations are logged for audit trail
         *     - One-time products don't require a selling plan ID
         *     - Price is optional for all APIs - if provided, it will be used; otherwise fetched from Shopify
         *     - Admin/Merchant can optionally provide explicit price (trusted backends)
         *     - Storefront typically omits price and lets server fetch from Shopify (security measure)
         */
        post: operations["add_line_item_v1_subscriptions_add_line_item_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Subscription
         * @description Create a new subscription contract for a customer.
         *
         *     Creates a subscription contract in Shopify with the specified products, billing schedule,
         *     delivery address, and payment method.
         *
         *     ### Args
         *
         *     - `customer_id`: Shopify customer ID (e.g., `gid://shopify/Customer/456`)
         *     - `lines`: List of products to include in the subscription:
         *
         *         - `product_variant_id`: The Shopify product variant ID
         *         - `quantity`: Quantity of this product
         *         - `current_price`: Price override (optional, see Price Calculation below)
         *         - `selling_plan_id`: Selling plan ID (optional, see Price Calculation below)
         *         - `custom_attributes`: Custom attributes for the line item
         *
         *     - `next_billing_date`: Next billing date in `YYYY-MM-DD` format (must be in the future)
         *     - `interval`: Billing interval (`DAY`, `WEEK`, `MONTH`, `YEAR`)
         *     - `interval_count`: Number of intervals between billings (default: 1)
         *     - `payment_method_id`: Shopify customer payment method ID
         *     - `delivery_address`: Delivery address containing:
         *
         *         - `first_name`, `last_name`: Recipient name
         *         - `address1`, `address2`: Street address
         *         - `city`, `province`, `country`, `zip`: Location details
         *         - `phone`: Contact phone number
         *         - `country_code`: ISO country code (e.g., `DE`, `US`)
         *
         *     - `delivery_method_type`: `shipping` or `local_delivery` (default: `shipping`)
         *     - `discount_codes`: List of discount codes to apply (optional)
         *     - `delivery_price`: Delivery price override (optional, see Delivery Price Calculation below)
         *     - `currency_code`: Currency code (default: `EUR`)
         *     - `custom_attributes`: Custom attributes for the contract (optional)
         *     - `caused_by`: Email or identifier of who initiated this action (for audit trail)
         *
         *     ### Price Calculation
         *
         *     Product prices are determined in the following order:
         *
         *     1. **If `current_price` is provided**: Uses the specified price directly (price override)
         *     2. **If `selling_plan_id` is provided**: Looks up the selling plan and applies its pricing policy
         *     3. **Otherwise**: Automatically finds a matching selling plan based on the subscription's
         *        `interval` and `interval_count`, then applies any discounts from that plan
         *
         *     When a selling plan is found, its pricing policy is applied to the variant's base price.
         *     For example, a selling plan with a 10% discount will reduce the variant price accordingly.
         *
         *     ### Delivery Price Calculation
         *
         *     Delivery price is determined in the following order:
         *
         *     1. **If `delivery_price` is provided**: Uses the specified price directly
         *     2. **If store config has `recalculate_shipping_rate_prior_to_charging=True`**: Sets to 0
         *        (delivery will be calculated at charge time)
         *     3. **Otherwise**: Calculates delivery rate using the store's delivery profiles based on
         *        the products and delivery address
         *
         *     ### Returns
         *
         *     **SubscriptionResponse** containing the created subscription contract with all its details.
         *
         *     ### Raises
         *
         *     - **HTTPException (400)**: Validation errors including:
         *
         *         - `InvalidDiscountCodeError`: Discount code does not exist or is not applicable to subscriptions
         *         - `InvalidPaymentMethodError`: Payment method is invalid or does not belong to the customer
         *         - `InvalidLineError`: Product variant does not exist
         *         - `InvalidBillingDateError`: Billing date is in the past
         *
         *     - **HTTPException (500)**: Internal server error
         *
         *     ### Notes
         *
         *     - Payment method must be valid and belong to the specified customer
         *     - Discount codes must be valid for subscriptions (one-time discounts will be rejected)
         *     - All operations are logged for audit trail with the `caused_by` identifier
         *     - Custom attributes `source` and `created_by` are automatically added to the contract
         */
        post: operations["create_subscription_v1_subscriptions_create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Subscription
         * @description Cancel a subscription contract.
         *
         *     This endpoint cancels all products in a subscription together. Any one-time add-on products are intelligently moved to another active subscription to ensure they're still delivered.
         *
         *     To cancel a specific line item instead of the entire subscription, use the `/line-items/cancel` endpoint.
         *
         *     ### Args
         *
         *     - `subscription_id`: ID of the subscription to cancel (required)
         *     - `reason`: Reason for cancelling (required for audit)
         *     - `caused_by`: Email/identifier of who initiated this (required for audit)
         *     - `customer_id`: ID of the customer that the subscription belongs to
         *     - `other_cancellation_reason`: Additional details about the cancellation reason (optional)
         *     - `move_one_times_to_next_eligible_date`: Whether to reassign one-time products to the next eligible date (default: True)
         *     - `permanent`: If True, permanently cancels in Shopify (status=CANCELLED, cannot reactivate).
         *       Default: False (status=PAUSED, can reactivate later)
         *
         *     ### Returns
         *
         *     **SubscriptionResponse** containing:
         *
         *     - `subscription`: The cancelled subscription contract details
         *
         *     ### Raises
         *
         *     - **HTTPException (404)**: Contract not found
         *     - **HTTPException (500)**: Failed to cancel the contract
         *
         *     ### Notes
         *
         *     - By default (`permanent=False`), subscriptions are paused and can be reactivated later
         *     - When `permanent=True`, the subscription is permanently cancelled in Shopify and cannot be reactivated
         *     - Cancellation metadata (reason, date) is stored on the contract for tracking
         *     - All actions are logged for audit trail purposes
         */
        post: operations["cancel_subscription_v1_subscriptions_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions/multi-update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Multi Update Subscription
         * @description Perform multiple subscription modifications in a single atomic operation.
         *
         *     Modify multiple aspects of a subscription at once: add, remove, or update products,
         *     and apply or remove discount codes. All changes are executed in parallel and committed
         *     atomically, so either all changes succeed or none are applied.
         *
         *     ### Args
         *
         *     - `subscription_id`: The subscription to modify
         *
         *         - Format: `gid://shopify/SubscriptionContract/123456789`
         *
         *     - `lines_to_add`: Products to add to the subscription
         *
         *         Each line item requires:
         *         - `product_variant_id`: The product variant to add
         *         - `quantity`: Number of items (default: 1)
         *         - `selling_plan_id`: Subscription pricing plan (optional)
         *         - `custom_attributes`: Additional metadata as key-value pairs (optional)
         *         - `type`: `"subscription"` (default) or `"one_time"` for next order only
         *
         *     - `lines_to_remove`: Line item IDs to remove
         *
         *         - Format: `gid://shopify/SubscriptionLine/uuid`
         *
         *     - `lines_to_update`: Line items to modify
         *
         *         - `line_item_id`: Which line to update (required)
         *         - `quantity`: New quantity (optional)
         *         - `product_variant_id`: Switch to a different variant (optional)
         *         - `selling_plan_id`: Change the pricing plan (optional)
         *
         *     - `discount_codes_to_apply`: Promotional discount codes to apply
         *
         *         - Format: Plain string codes (e.g., `["WELCOME10"]`)
         *
         *     - `discount_codes_to_remove`: Discount IDs to remove
         *
         *         - Format: `gid://shopify/SubscriptionManualDiscount/uuid`
         *
         *     - `caused_by`: Identifier for audit trail (default: `"merchant_api"`)
         *
         *     ### Returns
         *
         *     **SubscriptionResponse** containing:
         *
         *     - `subscription`: The fully updated subscription with all changes applied
         *
         *     ### Raises
         *
         *     - **HTTPException (400)**: No operations provided or invalid request
         *     - **HTTPException (500)**: Operation failed
         *
         *     ### Notes
         *
         *     - At least one operation must be provided
         *     - All operations execute in parallel for optimal performance
         *     - Changes are atomic - if any operation fails, none are applied
         */
        post: operations["multi_update_subscription_v1_subscriptions_multi_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/line-items/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Line Item
         * @description Cancel a specific line item from a subscription.
         *
         *     When cancelling a line item from a multi-product subscription, the system splits
         *     the subscription: the original keeps the remaining products, and a new subscription
         *     is created containing just the cancelled line item (in PAUSED or CANCELLED state).
         *
         *     For single-product subscriptions, this effectively cancels the entire subscription.
         *
         *     ### Args
         *
         *     - `cancel_request`: Request containing:
         *         - `subscription_id`: ID of the subscription containing the line item (required)
         *         - `line_item_id`: ID of the specific line item to cancel (required)
         *         - `reason`: Reason for cancelling (required for audit)
         *         - `caused_by`: Email/identifier of who initiated this (required for audit)
         *         - `customer_id`: ID of the customer that owns the subscription
         *         - `other_cancellation_reason`: Additional details about the cancellation reason (optional)
         *         - `move_one_times_to_next_eligible_date`: Whether to reassign one-time items
         *         - `permanent`: If True, permanently cancels (cannot reactivate). Default: False
         *
         *     ### Returns
         *
         *     **SubscriptionResponse** containing:
         *
         *     - `subscription`: The cancelled/split subscription contract details
         *
         *     ### Raises
         *
         *     - **HTTPException (404)**: Contract or line item not found
         *     - **HTTPException (500)**: Failed to cancel the line item
         */
        post: operations["cancel_line_item_v1_line_items_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Store Settings
         * @description Retrieve the complete configuration settings for your store.
         *
         *     Returns all store settings including billing configuration, bundling options,
         *     notification settings, shipping configuration, and delivery date settings.
         *
         *     ### Returns
         *
         *     **StoreSettingsResponse** containing:
         *
         *     - `settings`: Complete store configuration with the following sections:
         *
         *         - `is_active`: Whether the store is currently active
         *         - `billing`: Billing retry configuration
         *             - `failed_attempts`: Retry logic settings (max retries, days between retries)
         *             - `dont_attempt_when_out_of_stock`: Whether to skip billing when products are out of stock
         *         - `bundling`: Order bundling settings
         *             - `enabled`: Whether order bundling is enabled
         *         - `notification_settings`: Email notification configuration
         *             - `upcoming_delivery`: Lead time settings for delivery notifications
         *             - `notification_sender_email`: Sender email address
         *             - `default_notifications_language`: Default language for notifications
         *             - `urls`: Links to account page, legal notice, privacy policy, terms of service
         *             - `merchant_mail_address`: Merchant contact email
         *         - `shipping`: Shipping rate configuration
         *             - `apply_highest_shipping_rate`: Whether to use highest rate for bundled orders
         *             - `recalculate_shipping_rate_prior_to_charging`: Whether to recalculate rates before charging
         *         - `notification_templates`: SendGrid template IDs organized by template name and language
         *         - `delivery_date_settings`: Delivery scheduling configuration
         *             - `enable_schedule_by_delivery`: Whether scheduling is based on delivery date
         *             - `enable_checkout_widget`: Whether checkout widget scheduling is enabled
         *             - `custom_attribute_names`: Attribute names for delivery date and location
         *             - `custom_attribute_formats`: Date format configuration
         *             - `order_routing`: Order routing rules
         */
        get: operations["get_store_settings_v1_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/customers/storefront-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Storefront Token Endpoint
         * @description Directly provision a JWT access token for customer storefront access.
         *
         *     This endpoint requires authentication and creates a JWT access token that merchants
         *     can provide to their customers for storefront API access. The token automatically
         *     includes all active subscriptions for the customer fetched in real-time from Firestore.
         *
         *     This is direct provisioning - no refresh tokens or session management.
         *     Merchants control when and how tokens are provided to customers.
         *
         *     ### Args
         *
         *     - `customer_id`: Shopify customer ID to create token for (e.g., 'gid://shopify/Customer/456')
         *
         *     ### Returns
         *
         *     **CreateStorefrontTokenResponse** containing:
         *
         *     - `token`: JWT access token for storefront API access
         *     - `token_type`: Header name to use (always "X-Storefront-API-Token")
         *     - `expires_in`: Token expiry time in seconds (3600 = 1 hour)
         *
         *     ### Raises
         *
         *     - **HTTPException (500)**: Token creation failed
         *
         *     ### Notes
         *
         *     - Tokens expire after 1 hour
         *     - Token includes all active subscriptions for the customer
         *     - Customers use this token with `X-Storefront-API-Token: <token>` header in storefront API requests
         */
        post: operations["create_storefront_token_endpoint_v1_customers_storefront_tokens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Address
         * @description Shipping address information.
         */
        Address: {
            /**
             * Address1
             * @description First line of the address
             */
            address1?: string | null;
            /**
             * Address2
             * @description Second line of the address
             */
            address2?: string | null;
            /**
             * Zip
             * @description ZIP code
             */
            zip?: string | null;
            /**
             * City
             * @description City
             */
            city?: string | null;
            /**
             * Company
             * @description Company name
             */
            company?: string | null;
            /**
             * Country
             * @description Country
             */
            country?: string | null;
            /**
             * Country Code
             * @description Country code
             */
            country_code?: string | null;
            /**
             * Province Code
             * @description Province code. For some countries this is mandatory when creating a contract
             */
            province_code?: string | null;
            /**
             * First Name
             * @description First name
             */
            first_name?: string | null;
            /**
             * Last Name
             * @description Last name
             */
            last_name?: string | null;
            /**
             * Name
             * @description Full name
             */
            name?: string | null;
            /**
             * Phone
             * @description Phone number. Must be present when using local delivery.
             */
            phone?: string | null;
        };
        /**
         * AttributeNames
         * @description Defines the note attribute field names for storing dates and location.
         */
        AttributeNames: {
            /**
             * Expected Delivery Date
             * @description Attribute name for the delivery date attribute.
             * @default Expected Delivery Date
             */
            expected_delivery_date: string;
            /**
             * Location Id
             * @description Attribute name for storing the location ID.
             * @default Location ID
             */
            location_id: string;
        };
        /**
         * BaseCustomDiscount
         * @description Base model for custom discounts.
         */
        BaseCustomDiscount: {
            /** Title */
            title: string;
            /** Value */
            value: number;
            /**
             * Value Type
             * @enum {string}
             */
            value_type: "PERCENTAGE" | "FIXED";
            /**
             * Once Per Order
             * @default true
             */
            once_per_order: boolean;
            conditions?: components["schemas"]["DiscountConditions"] | null;
        };
        /**
         * BaseSubscriptionLineInput
         * @description Base input model for subscription line items in API requests.
         *
         *     Foundation for API endpoints that create or modify subscription line items.
         *     Contains core fields needed for any line item operation.
         */
        BaseSubscriptionLineInput: {
            /**
             * Product Variant Id
             * @description Shopify product variant ID
             */
            product_variant_id: string;
            /**
             * Selling Plan Id
             * @description Selling plan ID for subscription items
             */
            selling_plan_id?: string | null;
            /**
             * Quantity
             * @description Quantity of the item
             * @default 1
             */
            quantity: number;
            /**
             * Custom Attributes
             * @description Custom attributes for the line item
             */
            custom_attributes?: components["schemas"]["CustomAttribute"][] | null;
            /**
             * Type
             * @description Distinction on whether the new product should only be added to the next upcoming order as a one time or as a reagular subscription product
             * @default subscription
             */
            type: ("one_time" | "subscription") | null;
        };
        /**
         * BillingConfig
         * @description Configuration for billing operations.
         */
        BillingConfig: {
            failed_attempts: components["schemas"]["FailedAttemptsConfig"];
            /**
             * Dont Attempt When Out Of Stock
             * @description Prevents billing attempts if the product is out of stock
             * @default true
             */
            dont_attempt_when_out_of_stock: boolean;
        };
        /**
         * BillingPolicy
         * @description Billing policy with interval and frequency.
         */
        BillingPolicy: {
            /**
             * Interval
             * @description The frequency, it can be either: DAY, WEEK, MONTH or YEAR.
             */
            interval: string;
            /**
             * Interval Count
             * @description The number of intervals between each step in the given interval unit.
             */
            interval_count: number;
        };
        /**
         * BundlingConfig
         * @description Configuration for order bundling features.
         */
        BundlingConfig: {
            /**
             * Enabled
             * @description Indicates if bundling is enabled for the store
             * @default true
             */
            enabled: boolean;
        };
        /**
         * ChargeNowRequest
         * @description Request model for charging subscriptions immediately.
         */
        ChargeNowRequest: {
            /**
             * Subscription Ids
             * @description The base subscription IDs that should be charged now, irrespective of next charge date. These are in Shopify format, e.g. gid://shopify/SubscriptionContract/3259072718
             */
            subscription_ids?: string[] | null;
            /**
             * Next Billing Date Reference
             * @description After successfully charging the contract, calculate the next charge date either starting from today (i.e. today + interval), starting from next billing date (i.e. next_billing_date + interval) or simply leave it unchanged (leave_as_is)
             * @default original_next_billing_date
             * @enum {string}
             */
            next_billing_date_reference: "today" | "original_next_billing_date" | "leave_next_billing_date_unchanged";
            /**
             * Notify Customer About Failed Attempt
             * @description Specifies if customer should be informed about a failed attempt and be prompted to update their payment method
             * @default true
             */
            notify_customer_about_failed_attempt: boolean | null;
            /**
             * Caused By
             * @description Mandatory field for audit trail. Allows to override the triggered by field in logs to make sure that the logs reflect who actually did it.
             * @default Subscription Charge Now API
             */
            caused_by: string;
            /**
             * Customer Id
             * @description The customer that should be charged. Note that this will charge only the currently due subscriptions and will ignore subscription_ids and next_charge_date values.
             */
            customer_id?: string | null;
        };
        /**
         * ChargeNowResponse
         * @description Response model for charge-now endpoints.
         */
        ChargeNowResponse: {
            /**
             * Subscription Ids
             * @description List of subscription IDs that have been enqueued for charging
             */
            subscription_ids: string[];
        };
        /**
         * ContractDiscounts
         * @description Contract-specific discount information.
         */
        ContractDiscounts: {
            /**
             * Id
             * @description Shopify GID of the discount
             */
            id: string;
            /**
             * Recurring Cycle Limit
             * @description Number of times the discount can be applied on recurring orders
             */
            recurring_cycle_limit?: number | null;
            /**
             * Rejection Reason
             * @description Rejection reason if the discount is not valid anymore.
             */
            rejection_reason?: string | null;
            /**
             * Type
             * @description type of the discount. Can be AUTOMATIC_DISCOUNT, CODE_DISCOUNT or MANUAL
             */
            type: string;
            /**
             * Is Active
             * @description TRUE=discount is still active, FALSE=discount is not active anymore.
             */
            is_active: boolean;
            /**
             * Title
             * @description Title of the discount
             */
            title: string;
            /**
             * Usage Count
             * @description Number of times the discount has already been applied on recurring orders
             */
            usage_count: number;
            /**
             * Value
             * @description for percentage discounts -> value between 1-100, for fixed discounts = discount amount
             */
            value: number;
            /**
             * Value Type
             * @enum {string}
             */
            value_type: "PERCENTAGE" | "FIXED";
        };
        /**
         * ContractLine
         * @description Product line item within a subscription contract.
         *
         *     Represents a single product/variant that's part of a subscription.
         *     Extends Product with:
         *     - Line item ID for contract management
         *     - Title for display
         *     - Custom attributes for metadata
         *     - Current pricing for billing
         *
         *     Used in SubscriptionContractWithLines for tracking all products
         *     in a customer's subscription.
         */
        ContractLine: {
            /**
             * Product Id
             * @description Shopify GID of the product. e.g. gid://shopify/Product/XXX
             */
            product_id?: string | null;
            /**
             * Variant Id
             * @description Shopify GID of the variant. e.g. gid://shopify/ProductVariant/XXX
             */
            variant_id?: string | null;
            /**
             * Quantity
             * @description Ordered quantity of the product.
             */
            quantity?: number | null;
            /** @description Discounted price of the line */
            line_discounted_price?: components["schemas"]["Price"] | null;
            /**
             * Id
             * @description the shopify GID of the line of the contract.
             */
            id: string;
            /**
             * Title
             * @description the title of the line of the contract item
             */
            title: string;
            /**
             * Custom Attributes
             * @description Custom attributes of the contract item
             */
            custom_attributes?: components["schemas"]["CustomAttribute"][] | null;
            /** @description Current price of the contract item */
            current_price?: components["schemas"]["Price"] | null;
            /**
             * Variant Title
             * @description The title of the variant
             */
            variant_title?: string | null;
            /**
             * Variant Image
             * @description Link to the image of the variant
             */
            variant_image?: string | null;
        };
        /**
         * CreateStorefrontTokenRequest
         * @description Request model for creating a storefront token.
         */
        CreateStorefrontTokenRequest: {
            /**
             * Customer Id
             * @description The customer ID to create a token for
             */
            customer_id: string;
        };
        /**
         * CreateStorefrontTokenResponse
         * @description Response model for storefront token creation.
         */
        CreateStorefrontTokenResponse: {
            /**
             * Token
             * @description The JWT access token for storefront API access
             */
            token: string;
            /**
             * Token Type
             * @description The header name to use for authentication
             * @default X-Storefront-API-Token
             */
            token_type: string;
            /**
             * Expires In
             * @description Token expiry time in seconds from issuance
             */
            expires_in: number;
        };
        /**
         * CustomAttribute
         * @description Custom attribute for line items and contracts.
         */
        CustomAttribute: {
            /**
             * Key
             * @description key of the custom attribute. e.g. one_time_add_on
             */
            key: string | null;
            /**
             * Value
             * @description value of the custom attribute. e.g. TRUE/FALSE
             */
            value: string | null;
        };
        /**
         * CustomAttributeFormats
         * @description Configures the format for custom attribute values. Legacy: supports reading both formats.
         */
        CustomAttributeFormats: {
            /**
             * Expected Delivery Date
             * @description Date format for expected_delivery_date custom attribute.
             * @default %Y-%m-%d
             * @enum {string}
             */
            expected_delivery_date: "%Y-%m-%d" | "%Y/%m/%d";
        };
        /**
         * CustomDiscount
         * @description Represents a complete discount sequence.
         *
         *     It automatically sorts steps before validation, making it robust against unordered input.
         */
        CustomDiscount: {
            /**
             * Discount Id
             * @description shopify GID of the discount that the custom discount config belongs to
             */
            discount_id?: string | null;
            /**
             * Title
             * @description Discount title that was setup in eversubs admin
             */
            title?: string | null;
            /**
             * Description
             * @description Discount description that was setup in eversubs admin
             */
            description?: string | null;
            /**
             * Discount Classes
             * @description accepted values: ORDER, PRODUCT, SHIPPING
             */
            discount_classes?: string[] | null;
            /** @description accepted values: ORDER, PRODUCT, SHIPPING */
            initial_discount?: components["schemas"]["BaseCustomDiscount"] | null;
            /** Steps */
            steps?: components["schemas"]["DiscountStep"][];
            /**
             * Is Active
             * @description whether there is any active step on the discount
             * @default false
             */
            is_active: boolean;
        };
        /**
         * Customer
         * @description Customer model with extended information including discounts and bundling preferences.
         */
        Customer: {
            /**
             * Id
             * @description the shopify GID of the customer associated with the contract.
             */
            id: string;
            /**
             * Email
             * @description email of customer
             */
            email?: string | null;
            /**
             * First Name
             * @description first name of customer
             */
            first_name?: string | null;
            /**
             * Automatically Bundle Subscriptions
             * @description whether or not customer has bundling enabled. This will only be false if customer or customer support agent sets this metafield
             * @default true
             */
            automatically_bundle_subscriptions: boolean | null;
            /**
             * Customer Discounts
             * @description Manual discounts on the customer that will be applied to subscription orders if valid
             * @default []
             */
            customer_discounts: components["schemas"]["CustomDiscount"][] | null;
        };
        /**
         * CustomerPaymentMethod
         * @description Customer payment method information.
         */
        CustomerPaymentMethod: {
            /**
             * Id
             * @description the shopify GID of the customer payment method.
             */
            id?: string | null;
            /** @description Details about the payment method */
            instrument?: components["schemas"]["PaymentInstrument"] | null;
        };
        /**
         * DeliveryDateConfig
         * @description Top-level configuration for delivery and charge logic.
         */
        DeliveryDateConfig: {
            /**
             * Enable Schedule By Delivery
             * @description Whether order schedule is based on billing date or delivery date.
             * @default false
             */
            enable_schedule_by_delivery: boolean;
            /**
             * Enable Checkout Widget
             * @description Schedule recurring orders based on the first delivery date from checkout.
             * @default false
             */
            enable_checkout_widget: boolean;
            /** @description Default attribute names to be used. */
            custom_attribute_names: components["schemas"]["AttributeNames"];
            /**
             * @description Format configuration for custom attribute values.
             * @default {
             *       "expected_delivery_date": "%Y-%m-%d"
             *     }
             */
            custom_attribute_formats: components["schemas"]["CustomAttributeFormats"];
            /** @description set of rules for order routing mirroring shopify settings */
            order_routing: components["schemas"]["OrderRouting"] | null;
        };
        /**
         * DeliveryMethod
         * @description Delivery method with type, address and title.
         */
        DeliveryMethod: {
            /**
             * Type
             * @description Whether its using shipping or local delivery as a method.
             * @enum {string}
             */
            type: "shipping" | "local_delivery";
            /**
             * Phone
             * @description If type is local delivery the phone number must be present.
             */
            phone?: string | null;
            /** @description Shipping or local delivery method */
            address?: components["schemas"]["Address"] | null;
            /**
             * Title
             * @description Title of the delivery method. e.g. Kostenloser Versand / Standard Shipping
             * @default
             */
            title: string | null;
        };
        /**
         * DeliveryPolicy
         * @description Delivery policy with interval and frequency.
         *
         *     Fields are optional to handle non-recurring delivery policies (e.g., SellingPlanFixedDeliveryPolicy)
         *     which return empty objects from Shopify's GraphQL API.
         */
        DeliveryPolicy: {
            /**
             * Interval
             * @description The frequency, it can be either: DAY, WEEK, MONTH or YEAR.
             */
            interval?: string | null;
            /**
             * Interval Count
             * @description The number of intervals between each step in the given interval unit.
             */
            interval_count?: number | null;
        };
        /**
         * DiscountConditions
         * @description Conditions for applying discounts.
         */
        DiscountConditions: {
            /** @description only apply discount if order value exceeds minimum order value. */
            minimum_order_value?: components["schemas"]["MinumumOrderValue"] | null;
            /**
             * Apply To Collections
             * @description List of collection ids that the discount should be applied to
             * @default []
             */
            apply_to_collections: string[] | null;
            /**
             * Apply To Products
             * @description List of collection ids that the discount should be applied to
             * @default []
             */
            apply_to_products: string[] | null;
            /**
             * Apply To Product Variants
             * @description List of collection ids that the discount should be applied to
             * @default []
             */
            apply_to_product_variants: string[] | null;
            /**
             * Must Include Products
             * @description List of product ids that need to be present to apply the discount
             * @default []
             */
            must_include_products: string[] | null;
        };
        /**
         * DiscountStep
         * @description Discount step for progressive discounts.
         */
        DiscountStep: {
            /** Title */
            title: string;
            /** Value */
            value: number;
            /**
             * Value Type
             * @enum {string}
             */
            value_type: "PERCENTAGE" | "FIXED";
            /**
             * Once Per Order
             * @default true
             */
            once_per_order: boolean;
            conditions?: components["schemas"]["DiscountConditions"] | null;
            /** Step */
            step: number;
            /** Recurring Cycle Limit */
            recurring_cycle_limit: number;
            /**
             * Usage Count
             * @default 0
             */
            usage_count: number;
            /** Rejection Reason */
            rejection_reason?: string | null;
            /**
             * Is Active
             * @description whether this step is active
             * @default false
             */
            is_active: boolean;
        };
        /**
         * FailedAttemptsConfig
         * @description Configuration for handling failed billing attempts.
         */
        FailedAttemptsConfig: {
            /**
             * Notify On First Failure Only
             * @description Determines whether or not a customer should be emailed about failed billing attempts after the first one
             * @default false
             */
            notify_on_first_failure_only: boolean | null;
            /**
             * Max Retries
             * @description maximum number of retires. Default: 6
             * @default 6
             */
            max_retries: number | null;
            /**
             * Days Between Retries
             * @description Number of days between retry attempts default: 6
             * @default 6
             */
            days_between_retries: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LineUpdateInput
         * @description Input for updating an existing subscription line item.
         */
        LineUpdateInput: {
            /**
             * Line Item Id
             * @description The line item ID to update
             */
            line_item_id: string;
            /**
             * Quantity
             * @description New quantity for the line item
             */
            quantity?: number | null;
            /**
             * Product Variant Id
             * @description New product variant ID
             */
            product_variant_id?: string | null;
            /**
             * Selling Plan Id
             * @description New selling plan ID
             */
            selling_plan_id?: string | null;
        };
        /**
         * MerchantAddLineItemRequest
         * @description Merchant API request model for adding line items to subscription.
         */
        MerchantAddLineItemRequest: {
            /**
             * Subscription Id
             * @description The subscription ID
             */
            subscription_id: string;
            /**
             * Customer Id
             * @description Shopify customer ID for validation
             */
            customer_id: string;
            /**
             * Caused By
             * @description Email or identifier of who initiated this action (for audit trail)
             * @default merchant_api
             */
            caused_by: string;
            /** @description Line item details (price is optional, will be fetched from Shopify if not provided) */
            line_item: components["schemas"]["SubscriptionLineInputOptionalPrice"];
        };
        /**
         * MerchantCancelRequest
         * @description Merchant API request model for cancelling an entire subscription contract.
         */
        MerchantCancelRequest: {
            /**
             * Caused By
             * @description Email or identifier of who initiated this action (required for audit trail)
             */
            caused_by: string;
            /**
             * Customer Id
             * @description The GID of the customer that the subscription belongs to.
             */
            customer_id: string;
            /**
             * Move One Times To Next Eligible Date
             * @description Whether to move one times to the next eligible delivery for the customer or not. For merchants that only allow one subscription per customer this should always be set to False
             * @default true
             */
            move_one_times_to_next_eligible_date: boolean;
            /**
             * Subscription Id
             * @description The id of the subscription to cancel. This is in Shopify format, e.g. gid://shopify/SubscriptionContract/123456
             */
            subscription_id: string;
            /**
             * Reason
             * @description The reason for cancelling
             */
            reason: string;
            /**
             * Other Cancellation Reason
             * @description Additional details about the cancellation reason
             */
            other_cancellation_reason?: string | null;
            /**
             * Permanent
             * @description If True, permanently cancels in Shopify (status=CANCELLED). This action cannot be undone - the subscription cannot be reactivated. If False (default), pauses (status=PAUSED), allowing reactivation later.
             * @default false
             */
            permanent: boolean;
        };
        /**
         * MerchantCreateSubscriptionRequest
         * @description Merchant API request model for creating subscription contracts.
         */
        MerchantCreateSubscriptionRequest: {
            /**
             * Next Billing Date
             * @description Next billing date in YYYY-MM-DD format
             */
            next_billing_date: string;
            /**
             * Interval
             * @description Billing interval (DAY, WEEK, MONTH, YEAR)
             * @default WEEK
             * @enum {string}
             */
            interval: "DAY" | "WEEK" | "MONTH" | "YEAR";
            /**
             * Interval Count
             * @description Number of intervals between billings
             * @default 1
             */
            interval_count: number;
            /**
             * Payment Method Id
             * @description Shopify customer payment method ID
             */
            payment_method_id: string;
            /** @description Delivery address for the subscription */
            delivery_address: components["schemas"]["Address"];
            /**
             * Delivery Method Type
             * @description Whether to use local delivery or shipping as a delivery method
             * @default shipping
             * @enum {string}
             */
            delivery_method_type: "shipping" | "local_delivery";
            /**
             * Discount Codes
             * @description Discount codes to apply
             */
            discount_codes?: string[] | null;
            /**
             * Delivery Price
             * @description Delivery price. If not provided, will be calculated automatically based on store config.
             */
            delivery_price?: number | null;
            /**
             * Currency Code
             * @description Currency code (EUR, USD, etc.)
             * @default EUR
             */
            currency_code: string;
            /**
             * Custom Attributes
             * @description Custom attributes for the contract
             */
            custom_attributes?: components["schemas"]["CustomAttribute"][] | null;
            /**
             * Customer Id
             * @description Shopify customer ID (e.g., gid://shopify/Customer/456)
             */
            customer_id: string;
            /**
             * Lines
             * @description Line items for the subscription (price is optional, will be fetched from Shopify if not provided)
             */
            lines: components["schemas"]["SubscriptionLineInputOptionalPrice"][];
            /**
             * Caused By
             * @description Email or identifier of who initiated this action (for audit trail)
             * @default merchant_api
             */
            caused_by: string;
        };
        /**
         * MerchantLineItemCancelRequest
         * @description Merchant API request model for cancelling a specific line item.
         */
        MerchantLineItemCancelRequest: {
            /**
             * Caused By
             * @description Email or identifier of who initiated this action (required for audit trail)
             */
            caused_by: string;
            /**
             * Customer Id
             * @description The GID of the customer that the subscription belongs to.
             */
            customer_id: string;
            /**
             * Move One Times To Next Eligible Date
             * @description Whether to move one times to the next eligible delivery for the customer or not. For merchants that only allow one subscription per customer this should always be set to False
             * @default true
             */
            move_one_times_to_next_eligible_date: boolean;
            /**
             * Subscription Id
             * @description The id of the subscription to cancel. This is in Shopify format, e.g. gid://shopify/SubscriptionContract/123456
             */
            subscription_id: string;
            /**
             * Reason
             * @description The reason for cancelling
             */
            reason: string;
            /**
             * Other Cancellation Reason
             * @description Additional details about the cancellation reason
             */
            other_cancellation_reason?: string | null;
            /**
             * Permanent
             * @description If True, permanently cancels in Shopify (status=CANCELLED). This action cannot be undone - the subscription cannot be reactivated. If False (default), pauses (status=PAUSED), allowing reactivation later.
             * @default false
             */
            permanent: boolean;
            /**
             * Line Item Id
             * @description The id of the line item to cancel. This is in Shopify format, e.g. gid://shopify/SubscriptionLine/789012
             */
            line_item_id: string;
        };
        /**
         * MerchantMultiUpdateRequest
         * @description Request model for multi-update subscription endpoint.
         */
        MerchantMultiUpdateRequest: {
            /**
             * Subscription Id
             * @description The subscription contract ID to modify (format: gid://shopify/SubscriptionContract/123456789)
             */
            subscription_id: string;
            /**
             * Lines To Add
             * @description Products to add to the subscription
             */
            lines_to_add?: components["schemas"]["BaseSubscriptionLineInput"][] | null;
            /**
             * Lines To Remove
             * @description Line item IDs to remove (format: gid://shopify/SubscriptionLine/uuid)
             */
            lines_to_remove?: string[] | null;
            /**
             * Lines To Update
             * @description Line items to update (quantity, variant, or selling plan)
             */
            lines_to_update?: components["schemas"]["LineUpdateInput"][] | null;
            /**
             * Discount Codes To Apply
             * @description Discount codes to apply (format: plain code strings like 'SUMMER10')
             */
            discount_codes_to_apply?: string[] | null;
            /**
             * Discount Codes To Remove
             * @description Discount IDs to remove (format: gid://shopify/SubscriptionManualDiscount/uuid)
             */
            discount_codes_to_remove?: string[] | null;
            /**
             * Caused By
             * @description Identifier of who initiated this action (for audit trail)
             * @default merchant_api
             */
            caused_by: string;
        };
        /**
         * MinumumOrderValue
         * @description Minimum order value for discount conditions.
         */
        MinumumOrderValue: {
            /** Amount */
            amount: number;
            /** Currency */
            currency: string;
        };
        /**
         * NotificationSettingsConfig
         * @description Settings for customer notifications.
         */
        NotificationSettingsConfig: {
            upcoming_delivery: components["schemas"]["UpcomingDeliveryConfig"];
            /**
             * Notification Sender Email
             * @description email address used for sending notification emails
             */
            notification_sender_email?: string | null;
            /**
             * Default Notifications Language
             * @description Default language of the notifications
             */
            default_notifications_language: string;
            urls: components["schemas"]["UrlsConfig"];
            /**
             * Merchant Mail Address
             * @description The merchant's contact email address
             */
            merchant_mail_address?: string | null;
        };
        /**
         * NotificationTemplateData
         * @description Data for a single notification template.
         */
        NotificationTemplateData: {
            /**
             * Template Id
             * @description SendGrid template ID
             */
            template_id: string;
            /**
             * Template Is Active
             * @description Whether the template is active
             * @default true
             */
            template_is_active: boolean;
        };
        /**
         * OrderRouting
         * @description Contains the list of ordered routing rules.
         */
        OrderRouting: {
            /**
             * Rules
             * @description A list of routing rules to apply.
             */
            rules: components["schemas"]["RoutingRule"][];
        };
        /**
         * PaymentInstrument
         * @description Payment instrument infos. Differs between paypal, card and shop pay.
         */
        PaymentInstrument: {
            /**
             * Name
             * @description The name of the payment instrument
             */
            name?: string | null;
            /**
             * Paypal Account Email
             * @description If paypal is the instrument, paypal email.
             */
            paypal_account_email?: string | null;
            /**
             * Last Digits
             * @description The last digits number of the card if it is card payment.
             */
            last_digits?: number | null;
            /**
             * Masked Number
             * @description The masked number of the card if it is card payment.
             */
            masked_number?: string | null;
            /**
             * Brand
             * @description The brand of the card if it is card payment.
             */
            brand?: string | null;
            /**
             * Expiry Month
             * @description The expiration month of the card if it is card payment.
             */
            expiry_month?: number | null;
            /**
             * Expiry Year
             * @description The expiration month of the card if it is card payment.
             */
            expiry_year?: number | null;
            /**
             * Source
             * @description The source of the payment instrument for credit cards.
             */
            source?: string | null;
            /** @description Billing address associated with this payment method */
            billing_address?: components["schemas"]["Address"] | null;
        };
        /**
         * Price
         * @description Price information with currency and amount.
         */
        Price: {
            /**
             * Currency Code
             * @description Currency code for the price
             */
            currency_code: string;
            /**
             * Amount
             * @description Amount of the price
             */
            amount: number;
        };
        /**
         * RoutingRule
         * @description Defines a single rule for order routing.
         */
        RoutingRule: {
            /**
             * Priority
             * @description The order in which the rules are applied.
             */
            priority: number;
            /**
             * Rule Type
             * @description The type/name of the routing rule (e.g., CLOSEST_LOCATION).
             * @enum {string}
             */
            rule_type: "MINIMIZE_SPLIT_FULFILLMENTS" | "USE_LOCATION_METAFIELD" | "USE_RANKED_LOCATIONS" | "CLOSEST_LOCATION" | "STAY_WITHIN_DESTINATION_MARKET";
            /**
             * Description
             * @description A brief explanation of what the rule does.
             */
            description: string;
        };
        /**
         * ShippingConfig
         * @description Configuration for shipping options.
         */
        ShippingConfig: {
            /**
             * Apply Highest Shipping Rate
             * @description Determines if the highest shipping rate should be applied in applicable scenarios
             * @default true
             */
            apply_highest_shipping_rate: boolean;
            /**
             * Recalculate Shipping Rate Prior To Charging
             * @description Whether to recalculate the delivery rate prior to creating an order. This should only be enabled for stores that allow multiple subscriptions per customer
             * @default true
             */
            recalculate_shipping_rate_prior_to_charging: boolean;
        };
        /**
         * StoreConfig
         * @description Complete configuration for a store.
         */
        StoreConfig: {
            /**
             * Is Active
             * @description indicates if the store is active
             */
            is_active: boolean;
            /**
             * Shopify App Id
             * @description Shopify app ID for filtering selling plans to only use plans created by our app
             */
            shopify_app_id?: string | null;
            billing: components["schemas"]["BillingConfig"];
            bundling: components["schemas"]["BundlingConfig"];
            notification_settings: components["schemas"]["NotificationSettingsConfig"];
            shipping: components["schemas"]["ShippingConfig"];
            /**
             * Notification Templates
             * @description Notification templates grouped by template_name -> language
             */
            notification_templates?: {
                [key: string]: {
                    [key: string]: components["schemas"]["NotificationTemplateData"];
                };
            } | null;
            /** @description Settings for delivery date handling */
            delivery_date_settings: components["schemas"]["DeliveryDateConfig"];
        };
        /**
         * StoreSettingsResponse
         * @description Response model for store settings endpoint.
         */
        StoreSettingsResponse: {
            /** @description The complete store configuration */
            settings: components["schemas"]["StoreConfig"];
        };
        /**
         * SubscriptionContractFull
         * @description Full subscription contract with all fields.
         */
        SubscriptionContractFull: {
            /**
             * Id
             * @description the shopify GID of the contract.
             */
            id: string;
            /**
             * Next Billing Date
             * Format: date-time
             * @description the date where the contract is next to be billed
             */
            next_billing_date: string;
            /** @description Billing policy of the contract */
            billing_policy: components["schemas"]["BillingPolicy"] | null;
            /** @description customer data */
            customer: components["schemas"]["Customer"];
            /**
             * Lines
             * @description The lines of the contract (the first one is the original contract item. the following ones are either concatenated items or one time add ons
             */
            lines: components["schemas"]["ContractLine"][];
            /** @description Payment method of the customer */
            customer_payment_method?: components["schemas"]["CustomerPaymentMethod"] | null;
            /** @description Delivery policy of the contract */
            delivery_policy: components["schemas"]["DeliveryPolicy"];
            /**
             * Custom Attributes
             * @description Custom attributes of the contract
             */
            custom_attributes?: components["schemas"]["CustomAttribute"][] | null;
            /** @description Delivery method of the contract */
            delivery_method: components["schemas"]["DeliveryMethod"];
            /** @description The delivery price for each billing of the subscription contract. */
            delivery_price: components["schemas"]["Price"] | null;
            /**
             * Discounts
             * @description List of discounts on the contract. If they have a rejection reason will no longer be applied
             * @default []
             */
            discounts: components["schemas"]["ContractDiscounts"][] | null;
            /**
             * Revision Id
             * @description Revision id indicates a version of the contract, it's increasing but not necessarily every number is being used
             */
            revision_id: number;
            /**
             * Updated At
             * Format: date-time
             * @description The datetime, when the contract was last updated
             */
            updated_at: string;
            /**
             * Created At
             * Format: date-time
             * @description The datetime, when the contract was created
             */
            created_at: string;
            /**
             * Origin Order Id
             * @description The original checkout order that the contract has been created through. This is only correct for the contracts that have been created through eversubs.
             */
            origin_order_id?: string | null;
            /**
             * Status
             * @description The status of the contract.
             */
            status?: ("ACTIVE" | "CANCELLED" | "EXPIRED" | "FAILED" | "PAUSED" | "STALE") | null;
        };
        /**
         * SubscriptionLineInputOptionalPrice
         * @description API input for line items when creating new subscriptions.
         *
         *     Used by create_subscription endpoint. Price is optional because
         *     it can be determined from the selling plan unless overridden.
         */
        SubscriptionLineInputOptionalPrice: {
            /**
             * Product Variant Id
             * @description Shopify product variant ID
             */
            product_variant_id: string;
            /**
             * Selling Plan Id
             * @description Selling plan ID for subscription items
             */
            selling_plan_id?: string | null;
            /**
             * Quantity
             * @description Quantity of the item
             * @default 1
             */
            quantity: number;
            /**
             * Custom Attributes
             * @description Custom attributes for the line item
             */
            custom_attributes?: components["schemas"]["CustomAttribute"][] | null;
            /**
             * Type
             * @description Distinction on whether the new product should only be added to the next upcoming order as a one time or as a reagular subscription product
             * @default subscription
             */
            type: ("one_time" | "subscription") | null;
            /**
             * Current Price
             * @description Override price (only used if allow_price_override is true)
             */
            current_price?: number | null;
        };
        /**
         * SubscriptionResponse
         * @description Response model for subscription operations.
         */
        SubscriptionResponse: {
            subscription: components["schemas"]["SubscriptionContractFull"];
        };
        /**
         * SubscriptionsResponse
         * @description Response model for subscription queries with pagination support.
         */
        SubscriptionsResponse: {
            /** Subscriptions */
            subscriptions: components["schemas"]["SubscriptionContractFull"][];
            /**
             * Next Cursor
             * @description Cursor for pagination - pass this value to get the next page of results
             */
            next_cursor?: string | null;
        };
        /**
         * UpcomingDeliveryConfig
         * @description Configuration for upcoming delivery notifications.
         */
        UpcomingDeliveryConfig: {
            /**
             * Upcoming Delivery Lead Time
             * @description Lead time for 'upcoming delivery' notification
             */
            upcoming_delivery_lead_time: number;
        };
        /**
         * UrlsConfig
         * @description Configuration for various URLs used in the subscription system.
         */
        UrlsConfig: {
            /**
             * Account Page Url
             * @description Link to account page
             */
            account_page_url?: string | null;
            /**
             * Legal Notice Url
             * @description Link to legal notice url
             */
            legal_notice_url?: string | null;
            /**
             * Privacy Policy Url
             * @description Link to privacy policy
             */
            privacy_policy_url?: string | null;
            /**
             * Terms Of Service Url
             * @description Link to terms of service
             */
            terms_of_service_url?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    retrieve_subscriptions_v1_subscriptions_get: {
        parameters: {
            query?: {
                /** @description Maximum number of subscriptions to return (1-1000) */
                limit?: number;
                /** @description Pagination cursor from previous response. Use the `next_cursor` value from a previous response to fetch the next page of results. */
                cursor?: string | null;
                /** @description Shopify subscription contract ID for direct retrieval (e.g., 'gid://shopify/SubscriptionContract/123') */
                subscription_id?: string | null;
                /** @description Shopify customer ID to fetch all subscriptions for that customer (e.g., 'gid://shopify/Customer/456') */
                related_to_customer?: string | null;
                /** @description Contract status filter. Single status from: 'ACTIVE', 'CANCELLED', 'EXPIRED', 'FAILED', 'PAUSED', 'STALE' */
                status?: ("ACTIVE" | "CANCELLED" | "EXPIRED" | "FAILED" | "PAUSED" | "STALE") | null;
                /** @description Composite variant ID to filter subscriptions. Format: 'gid://shopify/ProductVariant/{id}|{type}' where type is either 'subscription' or 'one_time' (e.g., 'gid://shopify/ProductVariant/42638817034446|subscription') */
                variant_id?: string | null;
                /** @description Filter subscriptions with next billing date on or after this date (ISO format: '2024-01-15T00:00:00Z') */
                next_billing_date_min?: string | null;
                /** @description Filter subscriptions with next billing date on or before this date (ISO format: '2024-12-31T23:59:59Z') */
                next_billing_date_max?: string | null;
                /** @description Filter subscriptions created on or after this date (ISO format: '2024-01-01T00:00:00Z') */
                created_at_min?: string | null;
                /** @description Filter subscriptions created on or before this date (ISO format: '2024-12-31T23:59:59Z') */
                created_at_max?: string | null;
                /** @description Field to order results by. Options: 'next_billing_date', 'created_at' */
                order_by?: string;
                /** @description Sort direction: 'ASC' for ascending, 'DESC' for descending */
                order_by_direction?: "ASC" | "DESC";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    charge_now_v1_subscriptions_charge_now_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChargeNowRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChargeNowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_line_item_v1_subscriptions_add_line_item_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MerchantAddLineItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_subscription_v1_subscriptions_create_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MerchantCreateSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_subscription_v1_subscriptions_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MerchantCancelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    multi_update_subscription_v1_subscriptions_multi_update_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MerchantMultiUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_line_item_v1_line_items_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MerchantLineItemCancelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_store_settings_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreSettingsResponse"];
                };
            };
        };
    };
    create_storefront_token_endpoint_v1_customers_storefront_tokens_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStorefrontTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateStorefrontTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
